version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    #container_name: go_app
    image: devops-fullstack-app-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: employees
      DB_PORT: 5432
      ALLOWED_ORIGINS: "*"
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    #container_name: react_app
    image: devops-fullstack-app-frontend
    environment:
      - HOST=0.0.0.0
      - REACT_APP_SERVER_URL=http://34.30.207.18:8080/employees
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres-data: