name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - testing

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_REPO_BACKEND: sarveshsd/go-fullstack-backend
  DOCKERHUB_REPO_FRONTEND: sarveshsd/react-fullstack-frontend
  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get current version
      id: version
      run: |
        VERSION_FILE="version.txt"
        if [ ! -f $VERSION_FILE ]; then echo "0" > $VERSION_FILE; fi
        VERSION=$(cat $VERSION_FILE)
        VERSION=$((VERSION+1))
        echo $VERSION > $VERSION_FILE
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add $VERSION_FILE
        git commit -m "Bump version to $VERSION" || echo "No changes"
        git push origin ${{ github.ref_name }} || echo "Push failed"

    - name: Build & push backend Docker image
      run: |
        docker build -t $DOCKERHUB_REPO_BACKEND:${{ env.VERSION }} ./app/backend
        docker push $DOCKERHUB_REPO_BACKEND:${{ env.VERSION }}

    - name: Build & push frontend Docker image
      run: |
        docker build -t $DOCKERHUB_REPO_FRONTEND:${{ env.VERSION }} ./app/frontend
        docker push $DOCKERHUB_REPO_FRONTEND:${{ env.VERSION }}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup kubectl for EKS
      uses: aws-actions/eks-kubectl@v2
      with:
        cluster-name: sarvesh-eks
        region: us-east-1

    - name: Update backend deployment image
      run: |
        kubectl set image -f deployment/back.yml backend=$DOCKERHUB_REPO_BACKEND:${{ env.VERSION }} -n $K8S_NAMESPACE

    - name: Update frontend deployment image
      run: |
        kubectl set image -f deployment/front.yml frontend=$DOCKERHUB_REPO_FRONTEND:${{ env.VERSION }} -n $K8S_NAMESPACE

    - name: Deploy PV and PVC
      run: |
        kubectl apply -f deployment/pv.yml -n $K8S_NAMESPACE
        kubectl apply -f deployment/pvc.yml -n $K8S_NAMESPACE

    - name: Deploy Postgres
      run: |
        kubectl apply -f deployment/postgres.yml -n $K8S_NAMESPACE